# Generated by Django 5.0.7 on 2024-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default-food.png', upload_to='food-images/'),
        ),
    ]
