# Generated by Django 5.0.7 on 2024-07-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
