# Generated by Django 5.0.7 on 2024-08-05 15:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qty',
            new_name='food_qty',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='person_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddressOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('dom', models.CharField(max_length=100)),
                ('kvartira', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='orders.order')),
            ],
        ),
    ]
